### ISSUE TITLE
Gallery+ 14.0.0 - First four previews are displayed incorrectly

### ISSUE THREAD

**Issue by africanforest** [interfasys/galleryplus#18]
Since the update from Gallery+ 13 to Gallery+ 14 (via internal updater), the first 4 previews of each gallery (images in a directory) are displayed incorrectly. Contrary to all other previews of a gallery, they are cropped to squares (187px x 187px) and the lightboxed image is also cropped on black background.

This affects only the first 4 previews, no matter how the sort order is defined. Since my images are named in the form date_time, always the earliest files are getting cropped.

Strangely, the cropping is applied again and again with every new call of the gallery, so the previews are getting smaller each time.

Please note, that the black background is NOT the background color of the app window (i have set it to #ffffff in gallery.cfg), but part of the rendered image displayed in the lightbox! The different aspect ratio in the two screenshots is related to the different aspect ratio of the original images (the first one is 4:3, the second one is 3:2 from another gallery).

![gallery _14_full_view_1](https://cloud.githubusercontent.com/assets/1451511/10039784/bcde67b6-61d5-11e5-9906-dbb18f1e8426.jpg)
![gallery _14_full_view_2](https://cloud.githubusercontent.com/assets/1451511/10039785/bce01db8-61d5-11e5-995e-9f5e30bf1f1f.jpg)
![gallery _14_thumbnails](https://cloud.githubusercontent.com/assets/1451511/10039786/bce13d74-61d5-11e5-81dd-cb3eec5daa76.png)

**Comment by oparoz** [comment]
Thanks for the report :)

I need a bit more information. Is this on ownCloud 8.0 or 8.1? Do you see any browser error? Which browser?Anything in owncloud.log?
What are the original dimensions? What are your max_preview_x and may_preview_y settings?

**Comment by oparoz** [comment]
Also, are you using the files_archive app?

**Comment by africanforest** [comment]
Sorry, i forgot to provide more details.

I'm using OwnCloud 8.1.3.
No browser error.
Previews of galleries take ages to load as if they were loading for the very first time.
Funny, how previews of galleries are getting smaller with each call.

Now i browsed some galleries, after having deleted the logfile, but the only messages are so far:

#{"reqId":"Lw7HBUZMmYY5EXXyNEpq","remoteAddr":"80.110.122.41","app":"core","message":"maxX reduced from 2900 to 2048","level":0,"time":"2015-09-23T20:22:29+02:00","method":"GET","url":"\/cloud\/index.php\/apps\/galleryplus\/preview\/12327?c=4b3c9ed58fe85080405501fa81502101&width=2900&height=2900&requesttoken=JVFB03h0mR403lQIkMkq7yeRsk3nsd"}
{"reqId":"Lw7HBUZMmYY5EXXyNEpq","remoteAddr":"80.110.122.41","app":"core","message":"maxY reduced from 2900 to 2048","level":0,"time":"2015-09-23T20:22:29+02:00","method":"GET","url":"\/cloud\/index.php\/apps\/galleryplus\/preview\/12327?c=4b3c9ed58fe85080405501fa81502101&width=2900&height=2900&requesttoken=JVFB03h0mR403lQIkMkq7yeRsk3nsd"}

The images that i upload are all 1800px (max width/height).
I'm not using files_archive app, don't even know what it is for and how to get it.
Browser is Firefox 40.0.3 on Mac OSX 10.10.5.
No max_preview_x and may_preview_y settings defined. The defaults were good with version 13.

**Comment by africanforest** [comment]
Actually there must be a particular reason for the fact that always the first (file name!) previews are affected. Of course i have no clue, but isn't this a particularly conspicuous aspect?

**Comment by oparoz** [comment]
Could be:
1. a bug in Preview in `core` which can't cache the image for some reason
2. a bug in the files_locking, storage charts 2  app or any other app accessing the file system and which prevents access to the pictures
3. a bug in Gallery which can't save a fixed preview because it doesn't have access to the cache

I know it might not be easy to do on a production instance, but could you disable all other apps to rule out the possibility of another one interfering with the file system?

I've discarded a bug which would be triggered because you have a high DPI screen since it would affect all previews.

**Comment by oparoz** [comment]
Are these images all locally stored?

**Comment by africanforest** [comment]
Now i did the following:

1) First i disabled ALL apps except Gallery+.
2) I deleted all thumbnails.
3) I deleted the affected first four images of each gallery.
4) I uploaded new image files into a test folder.

This is the result so far:

Thumbnails were rebuild correctly on first run of the "cleaned" and new galleries. The first four thumbnails and previews are displayed correctly as well as all other ones. Galleries where i did not delete the first four images, still showed the issue - even with all apps disabled!

Now i concentrated only on those galleries where i had deleted the wrongly displayed images. I began to enable apps one by one in the order of my personal needs, while testing each time if the previews of gallery+ were still working:

Calendar Plus
PDF Viewer
Text Editor
Updater
Files Move
Tasks Plus
Contacts Plus
Rain Loop
OwnBackup
Log Reader
Pinit

Until this point, gallery+ 14 is working very well, all thumbnails and previews are displayed correctly.

These apps are still disabled (they were previously enabled):

Deleted files
Documents
External Sites
File Locking
Share Files
Versions
Bookmarks
MP3 Player

Maybe one of them is causing the problem, but currently i don't dare to enable one of these to test it. I just want to wait a couple of days and see if problem occurs again. If still all goes well, i will investigate further if one of these app maybe are interfering with gallery+14.

However, i'm still thinking that the issue must have something to do with some changes in Gallery+ 14, because all went well by running Gallery+ 13, even with all these apps enabled.

The screenshot below shows what happens, when the mouse cursor is moved near the upper edge of a wrongly displayed preview image: two ghostly gray squares appear, diagonally positioned. Maybe an indication?

![galleryplus14_ghost_preview](https://cloud.githubusercontent.com/assets/1451511/10069647/d48ec80a-62ad-11e5-81a8-ac8bf25bcb6a.jpg)

**Comment by oparoz** [comment]
> Galleries where i did not delete the first four images, still showed the issue - even with all apps disabled!

That's probably where the problem comes from. Maybe a corrupt filecache, but I just don't get why it only affects the first 4 pictures...

> However, i'm still thinking that the issue must have something to do with some changes in Gallery+ 14, because all went well by running Gallery+ 13, even with all these apps enabled.

Didn't you also update to 8.1.3? I don't know if you've had time to test v13 on that.

I don't exclude a problem with V14, of course, but you're the only one affected so far, so it's difficult to find the source :)

From your list of apps, I think we can exclude:
* Bookmarks
* MP3 Player
* Documents
* Share Files
* External Sites

I did notice some strange behaviours when plying with versions, but I'm not able to find a pattern.

**Comment by oparoz** [comment]
And regarding the ghostly area, it happens when you roll-over certain areas of a picture with a transparent background. I don't know if it's a browser feature or something hidden in the zooming app...

**Comment by africanforest** [comment]
All worked well today on my windows machine until...

When i started my MacBookPro with Retina display, the same behavior (cropped first 4 thumbnails and previews) was here again.

So, it's very likely that the issue is related to high resolution displays!

All galleries that worked nicely today on my windows PC, included the "cleaned" ones, showed the same bug again as soon as i opened them on MacBookPro Retina.

**Comment by oparoz** [comment]
Thanks, that will help. On my phone (453ppi), I don't get the shrinking thumbnail, but they're not resized properly, so I'll take a look.

It seems to only happen if it doesn't start with an album.

**Comment by oparoz** [comment]
Try this:

In preview/preview.php, look for the previewValidator method.

Replace

`($previewWidth !== $maxWidth || $previewHeight !== $maxHeight)`

with

`($previewWidth > $maxWidth || $previewHeight > $maxHeight)`


Hopefully, that's all it takes. You will need to clear your thumbnails again...

The problem happens because there is a hard limit which may be lower than what the highDPI client is asking for, so we keep fixing thumbnails which don't need fixing.

**Comment by africanforest** [comment]
Great, that fixed it! Thanks so much! :)

**Comment by oparoz** [comment]
Cool :) Thanks for helping with this!

**Comment by oparoz** [comment]
Small note to explain why only the first 4 pictures were affected. It's because it's actually the album view, one folder up, which was corrupting the thumbnails and those were being re-used later when looking inside the album.

**Comment by oparoz** [comment]
Fixed in V14.1
