### ISSUE TITLE
PHP Allowed memory size of 134217728 bytes exhausted with some images

### ISSUE THREAD

**Issue by fifh** [interfasys/galleryplus#21]
### Steps to reproduce
1. create a "pictures" folder in the root folder, copy a wide picture in this "pictures" folder (like the one I attach)
2. click on the Gallery+ icon
3. the spinning spinner will spin forever

another test : 
2. go to Files and then click on the Pictures folder
3. there is no preview for the picture, and when clicking on it, a message appear : "Error ! Could not generate a preview of this file"

### Expected behaviour
The picture and its preview should be displayed
The normal (non wide) pictures are well displayed
In the first test, the spinner is spinning indefinitely because the Gallery+ app should display a "pictures" icon (related to the "pictures" folder in the root folder) composed of a preview of the only one picture in the folder. And the app can't display the preview of this wide picture

### Server configuration
**Operating system**: 
Centos 7
**Web server:**
 Apache 2.4.6
**Database:**
MariaDB 5.5
**PHP version:**
5.4
**ownCloud version:** (see ownCloud admin page)
8.1.3
**Updated from an older ownCloud or fresh install:**
Updated from 8.1.1 (same behavior with the 8.1.1 version)
**List of activated apps:**
Gallery+ 14.1
Pictures/Gallery app disabled
Tried to disable File Locking with same results

**The content of config/config.php:**
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
    8 => 'OC\\Preview\\Movie',
    9 => 'OC\\Preview\\MSOffice2003',
    10 => 'OC\\Preview\\MSOffice2007',
    11 => 'OC\\Preview\\MSOfficeDoc',
    12 => 'OC\\Preview\\OpenDocument',
    13 => 'OC\\Preview\\PDF',
    14 => 'OC\\Preview\\Photoshop',
    15 => 'OC\\Preview\\Postscript',
    16 => 'OC\\Preview\\StarOffice',
  ),

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 40

**Operating system:**
Linux KDE

#### Web server error log
Some lines like this :
 - - [30/Sep/2015:16:12:48 +0200] "GET /index.php/apps/galleryplus/thumbnails?ids=16643%3B16814%3B16650%3B16812%3B16816%3B16824&scale=1&square=0&requesttoken=35pkwef7amJnFtygy%2BkNQT%2BRUSmoK1 HTTP/1.1" 200 55081 "https://.../index.php/apps/galleryplus/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:40.0) Gecko/20100101 Firefox/40.0"

#### ownCloud log (data/owncloud.log)
Some lines like this :
{"reqId":"","remoteAddr":"","app":"PHP","message":"Allowed memory size of 134217728 bytes exhausted (tried to allocate 31876 bytes) at \/var\/www\/html\/owncloud\/lib\/private\/image.php#512","level":3,"time":"Wed, 30 Sep 2015 16:12:10"}

**Comment by fifh** [comment]
![photo20150518t163247canon](https://cloud.githubusercontent.com/assets/13438427/10196034/fbeafb02-6790-11e5-9c10-092d7e1610ba.jpg)

**Comment by oparoz** [comment]
Hello, thanks for the report :)

The problem comes from your installation. You don't have enough memory to process the image and PHP crashes, leaving the Gallery app hanging because it never receives the thumbnail.

I should add something to the Wiki regarding the requirements since this is not the first time someone has experienced a problem with a large image.

It's best to give PHP 512MB of RAM.

**Comment by fifh** [comment]
Thanks for the reply !

You were right ! Previews were not created and pictures were not displayed if size (in pixel) exceeds 24 MP. 

I have changed "memory_limit" in php.ini and that's ok now.

Thanks !

**Comment by oparoz** [comment]
Great news :) I've updated the Gallery wiki and soon the one on here.

**Comment by cowai** [comment]
I have the same problem but for me It tries to allocate a lot more memory.
"Allowed memory size of 536870912 bytes exhausted (tried to allocate 13743895345 bytes) at DOCROOT/lib/private/image.php#690 "
I have 512mb as mem limit in php. I have also confirmed that php is indeed reporting 512mb as limit with <?php phpinfo();?>.

How can I figure out which image it stops at?

**Comment by oparoz** [comment]
New wiki article to help calculate the requirements:
https://github.com/owncloud/gallery/wiki/Defining-the-PHP-memory_limit

@cowai - You probably don't have an image which requires 13GB of memory to be processed. 

> How can I figure out which image it stops at?

Well, you can't unless you add loggers to the image class to output the name of the currently processed image. All we know is that it's a BMP.

I would open a bug report in `core` https://github.com/owncloud/core/issues since it seems the BMP creating method is eating all your RAM.
