### ISSUE TITLE
Release new Gallery+ versions for ownCloud older than N-1

### ISSUE THREAD

**Issue by oparoz** [interfasys/galleryplus#25]
I don't have the time to maintain branches which are older than what I use in production, which is N-1, where N is the currently released ownCloud version, but anybody can do it. 

8.1 and 8.0 are relatively similar.
8.2 and 8.1 have bigger gaps, like security fixes, tests and some GUI changes

### Process

* Cherry pick the fixes from the latest maintained branch. Careful with translations as master may contain files with some removed strings
* Test heavily
* Package
* Notify me

*Note: Should take about 2 hours*

----
@setnes @demattin

**Comment by fomalhaut78** [comment]
hi, backing this up for version 8.0.10 at least, ready to add a bounty if anyone interested

**Comment by oparoz** [comment]
@fomalhaut78 - Maybe post in the forums? Now both 8.0 and 8.1 are unmaintained.

**Comment by oparoz** [comment]
This issue was moved to oparoz/galleryplus#2
