### ISSUE TITLE
Display newest files first

### ISSUE THREAD

**Issue by NuxRo** [interfasys/galleryplus#26]
Hello,

Is there a way to display the newest files first by default? I make heavy use of the InstantUpload and every time I visit the gallery I need to modify the listing, it's annoying.

**Comment by oparoz** [comment]
Checkout this wiki article:
https://github.com/interfasys/galleryplus/wiki/Gallery--configuration#sorting

**Comment by NuxRo** [comment]
Hi,

I've created a config file as per that page, but it has not made a difference, whether it's "asc" or "des", it still shows the oldest first. What am I missing?

cat apps/galleryplus/gallery.cnf 
---
# Gallery+ configuration file
sorting:
  type: date
  order: des
  inherit: yes

**Comment by oparoz** [comment]
Could you hit F12 in your browser and go to the network tab to see if the call to the config endpoint returns a proper config?

**Comment by NuxRo** [comment]
Did that,
"GET /index.php/apps/galleryplus/config?" returns 200 OK and loads of other info. No obvious errors.

**Comment by oparoz** [comment]
Ah, I just took a 2nd look at your pasted conf. You've placed the config file in the apps folder, but you need to place it in your files.

Per example if you have a folder named "Instant Uploads", place gallery.cnf in that folder.

**Comment by NuxRo** [comment]
Thanks, 

Copying into the right place fixed it. I was hoping to make this a global thingy.
How would I go about doing this for all the albums? 

Showing the oldest first by default seems impractical, a problem which I have with owncloud generally and am trying to find a "fix".

**Comment by oparoz** [comment]
> How would I go about doing this for all the albums?

Simply place the file in the top folder.
One thing to remember is that shared folder won't have that order when opened by somebody else, unless you place a config file in that folder.

**Comment by NuxRo** [comment]
Thanks, that worked.
You wouldn't know how to do the same for the "files" display mode, would you? :-)
Owncloud seems to have got quite a few requests for this, but am yet to find a solution.

**Comment by oparoz** [comment]
Unfortunately, the Files app hasn't implemented any sort of config or saving system. The best thing to do would be to come up with a solution yourself or hire someone who can if those issues haven't been assigned a milestone yet
