### ISSUE TITLE
Gallery:create-thumbnails not appearing on occ

### ISSUE THREAD

**Issue by ZeManel2** [interfasys/galleryplus#28]
Hey,

I'm trying to generate thumbnails for my photos.
I've already installed galleryplus, but when I run "sudo -u www-data ./occ" it gives me a list of possible commands and it doesn't appear commands for gallery.

What is missing to do?

**Comment by oparoz** [comment]
Hello,

That feature has not been released yet. It's only available in this branch:https://github.com/owncloud/gallery/commits/create-thumbnail-command
