### ISSUE TITLE
Wrong Rotation

### ISSUE THREAD

**Issue by agronselimaj** [interfasys/galleryplus#29]
Photos taken with Samsung Galaxy Note 2, iPhone 5S, iPhone 6S when uploaded, OwnCloud or GalleryPlus generate thumbnails with wrong orientation.

Also, when you view that photo in fullscreen the orientation is wrong again.

Please see attached examples.
The same photos look just fine when you download them and view them with a photo viewing application, GwenView for KDE for Linux in my case.

On the last attached image you'll see detailed EXIF data in which orientation is "right,top" (6).

![oc-gp-001](https://cloud.githubusercontent.com/assets/6324431/12083406/f2f00f30-b270-11e5-9567-99f1d80c25f2.png)
![oc-gp-002](https://cloud.githubusercontent.com/assets/6324431/12083407/f2f28eea-b270-11e5-9008-c292ba154a9b.png)
![oc-gp-003](https://cloud.githubusercontent.com/assets/6324431/12083408/f2f2f6dc-b270-11e5-9d95-72d5ef1d264a.png)

Thanks,
//Agron

**Comment by oparoz** [comment]
Thank you very much for the report. It's a `core` issue as the app itself doesn't generate the previews.
Could you confirm that the previews are also wrong in the Files app (thumbnails)?
Would it be possible to get a couple of sample?

Once confirmed, it will be best to just copy and paste your report here: https://github.com/owncloud/core/issues

**Comment by agronselimaj** [comment]
yes, the preview in files app has wrong rotation too.
![p1](https://cloud.githubusercontent.com/assets/6324431/12123493/45dd0b28-b3af-11e5-8747-cd63dd60e1d3.png)

![p2](https://cloud.githubusercontent.com/assets/6324431/12123506/514cac48-b3af-11e5-88e2-cee9d0b1a673.png)

**Comment by oparoz** [comment]
Perfect, thanks for the confirmation.
So, please simply re-open the same ticket in `core` and the ownCloud team will take a look. Don't forget to provide a couple of original images in a file so that people can test this on their own setup.

BTW, you're sure you have the PHP EXIF module installed?

**Comment by agronselimaj** [comment]
Thanks for asking the PHP EXIF question. That lead me to find that *Exiv2*
is  required and it wasn't installed on my system.
https://wiki.archlinux.org/index.php/OwnCloud#Exif_support

Now, thumbnail in Files app and everything on GalleryPlus looks OK.

Thanks,
//Agron

**Comment by oparoz** [comment]
Ah, thanks for confirming :)
