### ISSUE TITLE
No pictures found Upload pictures in the files app to display them here

### ISSUE THREAD

**Issue by asterwing** [interfasys/galleryplus#33]
Gallery worked well, but for some reason no longer rendered photos.

Info:
No pictures found Upload pictures in the files app to display them here

OS win10
OwnCloud 8.0.4

**Comment by oparoz** [comment]
It could be for several reason. Some examples:
* Corrupt file
* Previews disabled
* Change in gallery.cnf

Please [use the template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) if you want me to try and figure it our.

**Comment by oparoz** [comment]
This issue was moved to oparoz/galleryplus#5
