### ISSUE TITLE
compatibility issue galleryplus-14.1-stable8 with OC 8.0.10

### ISSUE THREAD

**Issue by fomalhaut78** [interfasys/galleryplus#42]
## Bug report

when installing a compatibility error message is displayed in OC Apps tab, preventing installation to complete

### Steps to reproduce

1.decompress galleryplus-14.1-stable8.zip in the app folder
2.try to install from OC Apps panel

### Server configuration

**Operating system**: Windows 2008 Server R2, 64bit

**Web server:** iis7

**Database:** mysql

**PHP version:** 5.6

**ownCloud version:** 8.0.10 fresh install

**Are you using encryption:** yes

**Are you using custom gallery.cnf config files:** no

**Comment by oparoz** [comment]
Thanks for the report, I need to see what's reported in the ownCloud and browser log to see if that's something which can be easily fixed.

**Comment by fomalhaut78** [comment]
Hi,

attached OC log and the error displayed, tehre's nothing borwserside because I can't basically do anything, I just get the message once the Gallery+ folder gats copied in OC

many thanx for Your help, really appreciated

best,

Luca
________________________________
Da: Olivier Paroz [notifications@github.com]
Inviato: giovedì 5 maggio 2016 0.11
A: interfasys/galleryplus
Cc: Luca A. Giusti; Author
Oggetto: Re: [interfasys/galleryplus] compatibility issue galleryplus-14.1-stable8 with OC 8.0.10 (#42)


Thanks for the report, I need to see what's reported in the ownCloud and browser log to see if that's something which can be easily fixed.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/interfasys/galleryplus/issues/42#issuecomment-217019412>

{"reqId":"c5673b6e43dd1f431f1e75878c02dc8f","remoteAddr":"192.168.0.7","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-05-09T10:24:58+00:00"}
{"reqId":"57f8b4a7b5c26c09a2149b765b99d86b","remoteAddr":"217.56.107.210","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-05-09T10:25:10+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 168707","level":4,"time":"2016-05-09T10:25:57+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 160265","level":4,"time":"2016-05-09T10:25:57+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166049","level":4,"time":"2016-05-09T10:25:58+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166050","level":4,"time":"2016-05-09T10:25:58+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166051","level":4,"time":"2016-05-09T10:25:59+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166053","level":4,"time":"2016-05-09T10:25:59+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166054","level":4,"time":"2016-05-09T10:26:00+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166055","level":4,"time":"2016-05-09T10:26:00+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 169116","level":4,"time":"2016-05-09T10:26:00+00:00"}
{"reqId":"b0a77961f8da7433090e5ab9e45cfe02","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 170605","level":4,"time":"2016-05-09T10:26:01+00:00"}
{"reqId":"eb7f03145c345c1f1e029b4c6d2705ba","remoteAddr":"108.171.128.164","app":"index","message":"Exception: {\"Message\":\"Unable to generate a URL for the named route \\\"gallery_index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":\"#0 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\lib\\\\private\\\\route\\\\router.php(284): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('gallery_index', Array, false)\\n#1 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\lib\\\\private\\\\urlgenerator.php(42): OC\\\\Route\\\\Router->generate('gallery_index', Array)\\n#2 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\lib\\\\private\\\\helper.php(112): OC\\\\URLGenerator->linkToRoute('gallery_index', Array)\\n#3 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\lib\\\\public\\\\util.php(219): OC_Helper::linkToRoute('gallery_index', Array)\\n#4 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\apps\\\\gallery\\\\appinfo\\\\app.php(31): OCP\\\\Util::linkToRoute('gallery_index')\\n#5 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\lib\\\\private\\\\app.php(386): require('D:\\\\\\\\WEBSITES\\\\\\\\Lan...')\\n#6 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\settings\\\\ajax\\\\navigationdetect.php(9): OC_App::getAppNavigationEntries('gallery')\\n#7 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\lib\\\\private\\\\route\\\\route.php(135) : runtime-created function(1): require_once('D:\\\\\\\\WEBSITES\\\\\\\\Lan...')\\n#8 [internal function]: __lambda_func(Array)\\n#9 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\lib\\\\private\\\\route\\\\router.php(252): call_user_func('\\\\x00lambda_7618', Array)\\n#10 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\lib\\\\base.php(791): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#11 D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\index.php(44): OC::handleRequest()\\n#12 {main}\",\"File\":\"D:\\\\WEBSITES\\\\*website*\\\\owncloud\\\\3rdparty\\\\symfony\\\\routing\\\\Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator.php\",\"Line\":134}","level":4,"time":"2016-05-09T10:26:10+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 168707","level":4,"time":"2016-05-09T10:26:16+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 160265","level":4,"time":"2016-05-09T10:26:17+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166049","level":4,"time":"2016-05-09T10:26:17+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166050","level":4,"time":"2016-05-09T10:26:17+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166051","level":4,"time":"2016-05-09T10:26:17+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166053","level":4,"time":"2016-05-09T10:26:18+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166054","level":4,"time":"2016-05-09T10:26:18+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 166055","level":4,"time":"2016-05-09T10:26:18+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 169116","level":4,"time":"2016-05-09T10:26:19+00:00"}
{"reqId":"d5d248711b4eef1dbdf71092e96d235d","remoteAddr":"108.171.128.164","app":"core","message":"Unable to parse OCS content for app 170605","level":4,"time":"2016-05-09T10:26:19+00:00"}

**Comment by oparoz** [comment]
Thanks.

When did it break, with a Gallery+ update or an ownCloud update?

**Comment by fomalhaut78** [comment]
owncloud update, moved from 8.0.9 to 8.0.10 and when I tried to install G+ I got the "owncloud with a  version lower than 8.0.9 is required". tried also with a fresh 8.0.10 install to troubleshoot but got the same message

**Comment by oparoz** [comment]
Ah, but that should be easy to fix.

https://github.com/interfasys/galleryplus/blob/stable8/appinfo/info.xml#L39

change the 9 to 99

**Comment by fomalhaut78** [comment]
i thought it was simple but din't thought it was SO simple. It works , many thanx!

**Comment by oparoz** [comment]
Cool :)

Make sure you don't enable native_svg in your config. It's not safe in version earlier than 8.2.

**Comment by fomalhaut78** [comment]
will do :)
thanx again for Your support!
