### ISSUE TITLE
Image removing straight from the slideshow or the gallery (delete button)

### ISSUE THREAD

**Issue by tempico** [interfasys/galleryplus#43]
## Feature request

**User type**: Logged-in  user

**User level**: advanced

### Description
Image removing straight from the slideshow or the gallery (delete button).

### Benefit / value
In case of 1000 party pics in one folder it will save time to remove unneeded stuff from gallery without switching to "files" view. In future removing button functionality can be upgraded to removing with multiple file selection functionality.

### Risk / caveats
If pictures will be (re)moved to trash folder I do not expect any risk here.

### Sponsorship
$20-50 donation, but this depends.

**Comment by oparoz** [comment]
This wouldn't be too difficult to implement in the slideshow. Could you open the same issue in https://github.com/owncloud/gallery/issues/ please? That way we'll discuss potential solutions with the ownCloud community first.

**Comment by tempico** [comment]
Sure!
https://github.com/owncloud/gallery/issues/649

**Comment by oparoz** [comment]
Will be implemented in owncloud/gallery
