### ISSUE TITLE
PDF View in Gallery+ not shown

### ISSUE THREAD

**Issue by GebhardBalzer** [interfasys/galleryplus#44]
## Bug report
All files e.g. tif, png, eps... are shown in Gallery+ app but not PDF Files

### Steps to reproduce

1.PDF Thumbnails are shown in Files app
2. PDF Preview not shown in Gallery + 
1.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:**My SqL

**PHP version:**7.0.4

**ownCloud version:** (9.0.2)

**Updated from an older ownCloud or fresh install: fresh install on Windows7 with VMWare 12

**List of activated apps: Actifity Collaborative tags, Comments, deleted files, external Sites, Mail Template Editor, Notifivations, PDF Viewer Provision API, Share Files, Text Editor, Update notification, Versions, Viedo Player Gallery +, Activity Defaults

 
**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'oc6o3z2hx6cc',
  'asset-pipeline.enabled' => true,
  'passwordsalt' => 'yqOwOole/y3zVZ6/KSZjVNrCwnQ3eR',
  'secret' => 'Yj5AsgHrGZpO63/nuNR5s6rACobbGaKrmhPQO3BxEuj/FmF7',
  'trusted_domains' => 
  array (
    0 => 'localhost',

  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'owncloud',
  0 => 
  array (
    'path' => '/var/www/html/owncloud/apps',
    'url' => 'apps',
    'writable' => true,
  ),
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_Balzer',
  'dbpassword' => '',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_from_address' => '',
  'mail_domain' => '',
  'mail_smtphost' => '',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpport' => '465',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'loglevel' => 0,
  'appstore.experimental.enabled' => true,
  'maintenance' => false,
  'default_language' => 'de',
  'appstoreenabled' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'skeletondirectory' => '',
  'check_for_working_htaccess' => false,
  'enable_previews' => true,
  'preview_max_x' => 4096,
  'preview_max_y' => 4096,
  'preview_max_scale_factor' => 100,
  'preview_max_filesize_image' => 500,
  'max_filesize_animated_gifs_public_sharing' => 100,
  'enabledPreviewProviders' => 
  array (
   0 => 'OC\\Preview\\Illustrator',
   1 => 'OC\\Preview\\JPEG',
   2 => 'OC\\Preview\\Photoshop',
   3 => 'OC\\Preview\\BMP',
   4 => 'OC\\Preview\\Postscript',
   5 => 'OC\\Preview\\PNG',
   6 => 'OC\\Preview\\TIFF',
   7 => 'OC\\Preview\\PDF',
   8 => 'OC\\Preview\\GIF',
   9 => 'OC\\Preview\\SVG',
   10 => 'OC\\Preview\\Office',
 
  ),
);

**Are you using external storage, if yes which one:** local folder,.

**Are you using encryption:** no

**Are you using custom gallery.cnf config files:**no

### Client configuration

**Browser:** Safari, Crome, Firefox

**Operating system:** Mac OSX 10.9.5, Windows7 64 bit

## Feature request

**User type**: public user

**User level**: Beginners

### Sponsorship

 
**Are you a developer willing to implement this feature?**: no

**Can you sponsor the development of this feature or do you know somewone who can?**: no

**Comment by oparoz** [comment]
Unfortunately, that's [by design](https://github.com/interfasys/galleryplus/wiki#goals).

You can however participate [in this thread](https://github.com/owncloud/core/issues/17357), mentioning it's important for you to have a thumbnails view of your files.
