### ISSUE TITLE
Gallery+ display an empty page

### ISSUE THREAD

**Issue by effemmeffe** [interfasys/galleryplus#50]
### Steps to reproduce

1. Load some photos in a folder
2. Check that photos are shown with default Gallery app
3. Switch to Apps from top left menu
4. Disable Gallery app
5. Enable Gallery+ app
6. Choose Gallery+ from the top left menu
7. Look at a blank page: http://i.imgur.com/J1kI7ND.png

### Expected behaviour
Photos are displayed like in official Gallery app

### Actual behaviour
No photo is shown, just a blank page

### Server configuration

**Operating system**:
Ubuntu 14.04.4 LTS

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4.17

**ownCloud version:** (see ownCloud admin page or version.php)
9.0.2

**Updated from an older ownCloud or fresh install:**
fresh install

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.1.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - gallery
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc51i2odi7da",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "effemmeffe.ddns.net"
        ],
        "datadirectory": "\/media\/Cloud\/ownCloud\/",
        "overwrite.cli.url": "http:\/\/effemmeffe.ddns.net\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "ownCloudDB",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpport": "587",
        "log_type": "owncloud",
        "loglevel": 0,
        "log_rotate_size": 10485760,
        "appcodechecker": false,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\PNG",
            "1": "OC\\Preview\\JPEG",
            "2": "OC\\Preview\\GIF",
            "11": "OC\\Preview\\Illustrator",
            "12": "OC\\Preview\\Postscript",
            "13": "OC\\Preview\\Photoshop",
            "14": "OC\\Preview\\TIFF"
        }
    }
}

**Are you using external storage, if yes which one:** local folder, smb share, sftp, etc.
Yes, dropbox and google drive

**Are you using encryption:** yes/no
No

**Are you using custom gallery.cnf config files:** yes/no
Yes:

features:
  external_shares: no
  native_svg: yes
  background_colour_toggle: yes
sorting:
  type: date
  order: des
  inherit: yes

#### Web server error log
http://pastebin.com/c5nr2zHV

#### ownCloud log (data/owncloud.log)
Last lines: http://pastebin.com/RzrtnHTY

### Client configuration

**Browser:**
N/A

**Operating system:**
Windows 10

#### Browser log
N/A

**Comment by oparoz** [comment]
You've missed the fact that "files_mv" has to be disabled ;)

**Comment by effemmeffe** [comment]
I missed that for sure. But where should I read that?

**Comment by oparoz** [comment]
>I missed that for sure. But where should I read that?

It's a very good point actually...
All the information is here: https://apps.owncloud.com/content/show.php/Gallery%2B?content=169116
But this link is not published anywhere when you look at apps from within your cloud. The problem with the description is that it's not designed to communicate with users, so if I say don't use files_mv and then the dev fixes the problem, then people will be missing out as I have no way of changing the message without pushing a new version, which takes hours.

I'll try to add a FAQ to the wiki.

**Comment by effemmeffe** [comment]
Maybe besides the requirement section you could add an incompatibility section.
Plus, even on the link I can't find any reference to files_mv...

**Comment by oparoz** [comment]
>Plus, even on the link I can't find any reference to files_mv...

True, I updated the text for the last release because I didn't want to single out an app and make it look bad.
As a general rule, if you have issues with recommended apps, start by disabling experimental ones.

**Comment by oparoz** [comment]
I will modify that message

**Comment by effemmeffe** [comment]
Ok, thanks.
Now I did that and the behaviour changed: not an empty page anymore, but a circle spinning forever...

**Comment by oparoz** [comment]
Check the browser debugger and make sure Gallery is disabled.

**Comment by effemmeffe** [comment]
Gallery IS disabled.
Don't know what a "browser debugger" is.

**Comment by oparoz** [comment]
Press F12 and reload the page, you should get messages in red if it's a problem with loaded apps.

**Comment by effemmeffe** [comment]
I see a red line in the network tab referring to the following address:
http://effemmeffe.ddns.net/owncloud/apps/galleryplus/files/list?location=&mediatypes=image%2Fpng%3Bimage%2Fjpeg%3Bimage%2Fgif%3Bimage%2Fsvg%2Bxml&features=native_svg%3Bbackground_colour_toggle&etag
It took more than 1 minute to load.

Plus two errors in the console tab:
jquery.min.js?v=39e1ea1…:6 GET http://effemmeffe.ddns.net/owncloud/apps/galleryplus/files/list?location=&m…if%3Bimage%2Fsvg%2Bxml&features=native_svg%3Bbackground_colour_toggle&etag 504 (Timeout while reading response from Server)

And the circle is still spinning.
Could it be due to large number of images? My collection is 7.9 GB big with nearly 7000 files.

gallery.js?v=39e1ea1…:105 Uncaught TypeError: Cannot read property 'message' of undefined

**Comment by oparoz** [comment]
Yes, apparently, you have a large collection and the server is taking too long to respond, so you're never receiving the list of images. This can be fixed by changing a PHP variable to let scripts run for longer.
You also need to make sure you've enabled memcaching for file locking.

**Comment by effemmeffe** [comment]
Which variable are you referring to? Can you point me to the right direction in the doc?
I know nothing about memcaching, I'll read more on that, I'd rather not add more to that server if it will put load on it...

**Comment by oparoz** [comment]
https://stackoverflow.com/questions/7739870/increase-max-execution-time-for-php

memcaching will use RAM, but will massively speed up your cloud.

**Comment by effemmeffe** [comment]
Will use RAM when in use, right?
because that server is also my media player and I am the only user of the cloud. Can I be sure that while I'm watching some movie and I'm not using the cloud will not be too loaded to ruin the media player use?

**Comment by oparoz** [comment]
No, the RAM is blocked, but you don't need to allocate too much. Old tablets had 512MB RAM and could play movies just fine.

**Comment by effemmeffe** [comment]
Will investigate, thanks.
At worst I'll keep asking, if it's ok for you :)

**Comment by oparoz** [comment]
I would prefer it if you would ask at help.nextcloud.com since more people are available to reply and since a lot of questions have already been answered.

**Comment by effemmeffe** [comment]
Yes, I'll ask on the forum. But probably it's better for me to ask on the owncloud forum, because I decided not to migrate to nextcloud (yet)
Thanks.
