### ISSUE TITLE
extend media types, include videos

### ISSUE THREAD

**Issue by btk999** [interfasys/galleryplus#54]
Hi, 
it would be great, if the galleryplus app would support playinig videos.
Is it possible (and are more users than me interested in it) to include a video playback support?

kind regards

**Comment by oparoz** [comment]
Hello,
I'd love to, but it's not easy to do right, you can read the discussion taking place here:
https://github.com/owncloud/gallery/issues/194

**Comment by oparoz** [comment]
This issue was moved to oparoz/galleryplus#9
