### ISSUE TITLE
public share with allowed upload and password protection: endlees loading loop

### ISSUE THREAD

**Issue by simarilius** [interfasys/galleryplus#55]
I think this Bug is still in Gallery+
https://github.com/owncloud/core/issues/23066

had to switch back to the standard Gallery.

**Comment by ehsan7715** [comment]
yes Gallery+ is the problem 
my server is okay after disabling gallery+ App

**Comment by marsdenpete** [comment]
I'm having the same problem, have removed gallery + and the 5 second refresh was removed

**Comment by oparoz** [comment]
This is a duplicate of https://github.com/interfasys/galleryplus/issues/51 which was fixed 3 weeks ago in master. I just need to release a new package, hopefully today.
