### ISSUE TITLE
PERMISSIONS ignored with Gallery+ v15

### ISSUE THREAD

**Issue by jordiaguilarupc** [interfasys/galleryplus#56]
### Steps to reproduce
1. Install and Activate the Gallery+ App
2. User A shares a folder with User B (or shares link for any user) unchecking editing permissions
3. User B enters to shared folder and activates the Gallery+ View

### Expected behaviour
User B should not be able to upload new documents to the folder neither to delete existing files (because User A shared it with reading permission only)

### Actual behaviour
User B can either upload new files and delete existing files if he's using Gallery+  (with normal files view it doesn't happend and with Gallery also the permissions are respected, but not with Gallery+)

### Server configuration

**Operating system**: Armbian 5.16

**Web server:** Apache

**Database:** MySql

**PHP version:** 5...

**ownCloud version:** 9.0.3

**Updated from an older ownCloud or fresh install: fresh

**List of activated apps:** none

**Are you using external storage, if yes which one:** USB drive mounted

**Are you using encryption:** no

**Are you using custom gallery.cnf config files:** no

Thank you so much !

**Comment by oparoz** [comment]
Thanks for reporting this issue. Unfortunately, I can't reproduce it, so I'm going to need more information.

1) Are both users on the same server?
2) Are the files on the USB drive?

In Gallery+ 15.1.1, I don't see the delete icon, so I can't remove any images and when I upload a new file, I get a message at the end of the process telling me that uploading has failed.

**Comment by jordiaguilarupc** [comment]
1) Yes, both users are on the same servers
2) Yes, the files are stored on the USB drive

I'll reproduce it again tonight (I'll reinstall the App and so on) and I'll comment here the result

**Comment by oparoz** [comment]
OK and if it's still a problem, please add some information about how the USB drive is mounted.

**Comment by jordiaguilarupc** [comment]
I reinstalled Gallery+ and it works fine.. I don't understand what could happend.. I'm sure about the test I did.. 

The USB is mounted through /etc/fstab .. it's an ext4 partition mounted with "defaults 0 2" parameters..

Well.. it seems it's not a bug, it's working fine..

Thank you for your support !

**Comment by oparoz** [comment]
Maybe it was a problem with an earlier version of either Gallery+ or oC/NC or maybe you've simply unticked the share box instead of the edit one, it can be confusing when the window is not wide enough.
But I'm glad you're not experiencing the issue any more :)
