### ISSUE TITLE
Rendering Problems (?) with Firefox after FF upgrade

### ISSUE THREAD

**Issue by Bodenseematze** [interfasys/galleryplus#8]
I lately upgraded my firefox installation to 40.0.2 - since then (maybe already with 40.0 - I don't exactly know with which firefox version I successfully opened my owncloud installation) I have problems with the galleryplus in my 8.0.5 owncloud installation.

In directories with picture subdirectories it doesn't show the collecting pictures on the directory symbols - only a folder symbol (and sometimes not even that).
In directories with pictures it always spins the wheel without showing any picture :o
Here's how it looks now in Firefox 40:
![oc8_ff](https://cloud.githubusercontent.com/assets/13251886/9540765/68950dc2-4d62-11e5-86f5-8080c7ebc9d9.jpg)

In Chrome / Iron and IE everything works correctly as always:
![oc8_iron](https://cloud.githubusercontent.com/assets/13251886/9540780/78a18bdc-4d62-11e5-93c1-484d19d9c087.jpg)

What's going on here? :cry:
Is that a (new) rendering problem in FF?

BTW, I don't see any related log entries in OC for that...

**Comment by oparoz** [comment]
Thanks for the report!

Firefox 40 has introduced some new security checks and I need to see if that's what's causing the issue.

**Comment by ilsi** [comment]
This bug could be related with https://github.com/owncloud/gallery/issues/272

**Comment by oparoz** [comment]
Fixed via https://github.com/interfasys/galleryplus/commit/f0dbe362fb4fe375b72980500398cdfbb0531c3a

**Comment by oparoz** [comment]
It's the same bug. oC 8.0 doesn't let us manipulate the CSP, but I've imlemented a fix which will be in the next release.
